on:
  workflow_call:
    inputs:
      project-folder:
        type: string
        default: .
      service-folder:
        required: true
        type: string
      image-tag:
        required: true
        type: string

    secrets:
      registry-user:
        required: true
      registry-token:
        required: true
      PAT_TOKEN:
        required: true
    
jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: |
          unset DOCKER_HOST
          echo "${{ secrets.registry-token }}" | docker login "${{ vars.CI_REGISTRY }}" -u "${{ secrets.registry-user }}" --password-stdin

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Create nuget.config
        env:
          NUGET_PROVIDER: ${{ vars.NUGET_PROVIDER }}
          REGISTRY_USER: ${{ secrets.registry-user }}
          NUGET_CONFIG: ${{ vars.NUGET_CONFIG }}
        run: |
          echo "$NUGET_CONFIG" | envsubst > ${{ inputs.project-folder }}/nuget.config

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.project-folder }}
          file: ${{ inputs.project-folder }}/${{ inputs.service-folder }}/Dockerfile
          push: true

          tags: |
            ${{ inputs.image-tag }}

          cache-from: type=gha,scope=${{ github.repository }}
          cache-to: type=gha,mode=max,scope=${{ github.repository }}
