on:
  workflow_call:
    inputs:
      service-folder:
        required: true
        type: string
      service-name:
        required: true
        type: string
    
jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: |
          unset DOCKER_HOST
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login "${{ vars.CI_REGISTRY }}" -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Create nuget.config
        if: ${{ vars.NUGET_CONFIG != '' }}
        env:
          NUGET_CONFIG: ${{ vars.NUGET_CONFIG }}          
          NUGET_PROVIDER: ${{ vars.NUGET_PROVIDER }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          echo "$NUGET_CONFIG" | envsubst > ${{ vars.PROJECT_FOLDER }}/nuget.config

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ vars.PROJECT_FOLDER }}
          file: ${{ vars.PROJECT_FOLDER }}/${{ inputs.service-folder }}/Dockerfile
          push: true

          tags: |
            ${{ vars.CI_REGISTRY }}/${{ github.repository }}/${{ inputs.service-name }}:${{ github.run_number }}

          cache-from: type=gha,scope=${{ github.repository }}
          cache-to: type=gha,mode=max,scope=${{ github.repository }}
