on:
  workflow_call:
    inputs:
      service-folder:
        required: true
        type: string
      service-name:
        required: true
        type: string        

    secrets:
      registry-user:
        required: true
      registry-token:
        required: true
    
jobs:
  resolve-env:
    uses: PANiXiDA-Infrastructure/ci-cd/.github/workflows/resolve-environment.yml@main

  run:
    needs: resolve-env
    environment: ${{ needs.resolve-env.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: |
          unset DOCKER_HOST
          echo "${{ secrets.registry-token }}" | docker login "${{ vars.REGISTRY_URL }}" -u "${{ secrets.registry-user }}" --password-stdin

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Create nuget.config
        uses: PANiXiDA-Infrastructure/ci-cd/.github/actions/create-nuget-config@main

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ vars.PROJECT_FOLDER }}
          file: ${{ vars.PROJECT_FOLDER }}/${{ inputs.service-folder }}/Dockerfile
          push: true

          tags: |
            ${{ vars.REGISTRY_URL }}/${{ github.repository }}/${{ inputs.service-name }}:${{ vars.ENV_SUFFIX }}-${{ github.run_number }}

          cache-from: type=gha,scope=${{ github.repository }}
          cache-to: type=gha,mode=max,scope=${{ github.repository }}
