on:
  workflow_call:
    inputs:
      project-folder:
        type: string
        default: .
      service-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string

    secrets:
      registry-user:
        required: true
      registry-token:
        required: true
    
jobs:
  docker_build:
    runs-on: ubuntu-latest

    outputs:
      image_build_tag: ${{ inputs.image-build-tag }}
      image_latest_env: ${{ inputs.image-latest-env-tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: |
          unset DOCKER_HOST
          echo "${{ secrets.registry-token }}" | docker login "${{ vars.CI_REGISTRY }}" -u "${{ secrets.registry-user }}" --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.project-folder }}
          file: ${{ inputs.project-folder }}/Dockerfile
          push: true

          tags: |
            ${{ inputs.image-tag }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
