on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dotnet-format
        run: |
          dotnet tool install -g dotnet-format || true
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run .NET format
        working-directory: ${{ vars.PROJECT_FOLDER }}
        run: |
          dotnet format --verify-no-changes --severity warn
